######################## default configuration ####################
baseURL = "http://halseylabs.com/demo/"
languageCode = "en"
title = "AppsFlyer | Demo Site"
theme = "hargo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  # [[params.plugins.js]]
  # link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Products"
  URL = "products"
  weight = 1

  # [[menu.main]]
  # name = "Blog"
  # URL = "blog"
  # weight = 2

  # [[menu.main]]
  # name = "FAQ"
  # URL = "faq"
  # weight = 3

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Products"
  URL = "products"
  weight = 1

  # [[menu.footer]]
  # name = "Blog"
  # URL = "blog"
  # weight = 2

  # [[menu.footer]]
  # name = "FAQ"
  # URL = "faq"
  # weight = 3

  [[menu.footer]]
  name = "Terms & Conditions"
  URL = "terms-conditions"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/appsflyerlogo.png"
home = "Home"
# Meta data
description = "This is a demo page for AppsFlyer offerings."
author = "AppsFlyer"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "32.16443083113449"
mapLongitude = "34.810849898354626"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "UA-184104478-1" # Your ID
# Contact Information
mobile = "+972-9-768-1949"
email = "support@appsflyer.com"
location = "Herzliya, Israel"
# QR Code
qrcode = "images/qr_code_scanme.png"
# copyright
copyright = "AppsFlyer | Copyright &copy; 2020 All Rights Reserved | www.appsflyer.com"
# Snipcart Credentials
# snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
# currencySymbol = "$"

  # Preloader
  [params.preloader]
  enable = false
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  # [params.rating]
  # enable = true
  # websiteID = "444334"
  # publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-twitter-alt"
  link = "https://twitter.com/AppsFlyer"
  
  [[params.social]]
  icon = "ti-facebook"
  link = "https://www.facebook.com/AppsFlyer/"

  [[params.social]]
  icon = "ti-instagram"
  link = "https://www.instagram.com/lifeatappsflyer/"

  [[params.social]]
  icon = "ti-linkedin"
  link = "https://www.linkedin.com/company/appsflyer/"

  [[params.social]]
  icon = "ti-youtube"
  link = "https://www.youtube.com/c/Appsflyer"

  [[params.social]]
  icon = "ti-github"
  link = "https://github.com/AppsFlyer"

  # Contact Form
  [params.contact]
  formAction = "https://formspree.io/f/meqplkde" # contact form works with formspree.io
